# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFailedRegister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_failedRegister(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1440, 809)
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "firstname").click()
    self.driver.find_element(By.ID, "firstname").send_keys("test")
    self.driver.find_element(By.ID, "lastname").send_keys("test")
    self.driver.find_element(By.ID, "username").send_keys("test")
    self.driver.find_element(By.ID, "email").send_keys("test@example.com")
    self.driver.find_element(By.ID, "password").send_keys("password")
    self.driver.find_element(By.ID, "password_confirm").send_keys("passwor")
    self.driver.find_element(By.CSS_SELECTOR, ".border-0").click()

  
